# Generated by Django 5.1.7 on 2025-03-24 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasepost',
            name='created_at',
        ),
        migrations.AddField(
            model_name='releasepost',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_art/'),
        ),
        migrations.AddField(
            model_name='releasepost',
            name='release_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='releasepost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. boom bap, chill, 209)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='releasepost',
            name='track_preview',
            field=models.FileField(blank=True, null=True, upload_to='track_previews/'),
        ),
        migrations.AlterField(
            model_name='releasepost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
