# Generated by Django 5.1.7 on 2026-02-23 03:16

import django.utils.timezone
import fliphouserecords.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_remove_releasepost_created_at_releasepost_album_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the link', max_length=200)),
                ('url', models.URLField(help_text='Full URL including https://', max_length=500)),
                ('description', models.CharField(blank=True, help_text='Short description (optional)', max_length=300, null=True)),
                ('category', models.CharField(choices=[('artist', 'Artist'), ('label', 'Label'), ('studio', 'Studio'), ('store', 'Store'), ('other', 'Other')], default='other', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Artist name (required)', max_length=200)),
                ('hometown', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('headshot', models.ImageField(blank=True, null=True, storage=fliphouserecords.storage_backends.MediaStorage(), upload_to='artist_headshots/')),
                ('soundcloud_url', models.URLField(blank=True, max_length=500, null=True)),
                ('linktree_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('spotify_url', models.URLField(blank=True, max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text='bcrypt hash of the password', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_link', models.URLField(blank=True, max_length=500, null=True)),
                ('flyer', models.ImageField(blank=True, null=True, storage=fliphouserecords.storage_backends.MediaStorage(), upload_to='event_flyers/')),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='WallCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_data', models.TextField(default='{}', help_text="JSON: { 'x,y': '#rrggbb', ... }")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='releasepost',
            name='album_art',
            field=models.ImageField(blank=True, null=True, storage=fliphouserecords.storage_backends.MediaStorage(), upload_to='album_art/'),
        ),
        migrations.AlterField(
            model_name='releasepost',
            name='track_preview',
            field=models.FileField(blank=True, null=True, storage=fliphouserecords.storage_backends.MediaStorage(), upload_to='track_previews/'),
        ),
    ]